[project]
name = "aero-hand-open"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "esptool>=5.1.0",
    "pyserial>=3.5",
]
